version: '3.8'

services:
  go:
    container_name: go
    build:
      context: ./golang
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8082:8080
    volumes:
      - type: bind
        source: ./golang/src
        target: /go/src
    networks:
      - golang_network

networks:
  golang_network:
    external: true